# Generated by Django 5.0.6 on 2024-09-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendences',
            name='in_time',
        ),
        migrations.RemoveField(
            model_name='attendences',
            name='out_time',
        ),
        migrations.AddField(
            model_name='attendences',
            name='status',
            field=models.CharField(default='Absent', max_length=50),
        ),
    ]
