# Generated by Django 5.0.6 on 2024-09-05 10:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_admin', '0003_alter_allemployee_user_alter_allmanagers_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_hours', models.DurationField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Full Day', 'Full Day'), ('Half Day', 'Half Day'), ('Absent', 'Absent')], default='Absent', max_length=50)),
                ('aemp', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='erp_admin.allemployee')),
                ('am', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='erp_admin.allmanagers')),
                ('branch_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_admin.branches')),
            ],
        ),
    ]
