# Generated by Django 5.0.6 on 2024-09-07 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_admin', '0004_attendences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendences',
            name='aemp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_admin.allemployee'),
        ),
        migrations.AlterField(
            model_name='attendences',
            name='am',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_admin.allmanagers'),
        ),
    ]
