# Generated by Django 5.0.6 on 2024-09-30 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_admin', '0005_alter_attendences_aemp_alter_attendences_am'),
    ]

    operations = [
        migrations.CreateModel(
            name='leadsentry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.TextField(max_length=1000)),
                ('email', models.TimeField(blank=True, max_length=1000)),
                ('phone', models.CharField(blank=True, max_length=1000)),
                ('companyname', models.CharField(max_length=500)),
                ('jobtitle', models.CharField(max_length=500)),
                ('website', models.TextField(blank=True)),
                ('source', models.TextField(blank=True)),
                ('followup_date', models.DateField(blank=True)),
                ('followup_method', models.CharField(max_length=1200)),
                ('budget', models.CharField(max_length=20000)),
                ('leadstatus', models.CharField(blank=True, max_length=1200)),
                ('leadowner', models.EmailField(blank=True, max_length=1200)),
            ],
        ),
        migrations.CreateModel(
            name='purchasereport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchaseid', models.CharField(max_length=100000)),
                ('dateof_purchase', models.DateField()),
                ('vendor_name', models.CharField(max_length=10000)),
                ('vendor_contact', models.CharField(max_length=10000)),
                ('product_name', models.CharField(max_length=10000)),
                ('product_category', models.CharField(max_length=10000)),
                ('quantity_purchase', models.CharField(max_length=100000)),
                ('payment_method', models.CharField(choices=[('cash on delivery', 'Cash On Delivery'), ('online', 'Online')], max_length=500)),
                ('unitprice', models.CharField(max_length=10000)),
                ('total_purchasecost', models.CharField(max_length=100000)),
                ('status', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='salesreport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=100000)),
                ('dateof_sale', models.DateField()),
                ('customer_name', models.CharField(max_length=10000)),
                ('customer_contact', models.CharField(max_length=10000)),
                ('product_name', models.CharField(max_length=10000)),
                ('product_category', models.CharField(max_length=10000)),
                ('quantity_sold', models.CharField(max_length=100000)),
                ('payment_method', models.CharField(choices=[('cash on delivery', 'Cash On Delivery'), ('online', 'Online')], max_length=500)),
                ('unitprice', models.CharField(max_length=10000)),
                ('total', models.IntegerField()),
                ('status', models.CharField(max_length=10000)),
            ],
        ),
    ]
