# Generated by Django 5.0.6 on 2024-10-03 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_admin', '0007_todowork_delete_salesreport_alter_leadsentry_budget_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='salesreport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=100000)),
                ('dateof_sale', models.DateField()),
                ('customer_name', models.CharField(max_length=10000)),
                ('customer_contact', models.CharField(max_length=10000)),
                ('product_name', models.CharField(max_length=10000)),
                ('product_category', models.CharField(blank=True, max_length=10000)),
                ('quantity_sold', models.CharField(max_length=100000)),
                ('payment_method', models.CharField(choices=[('cash on delivery', 'Cash On Delivery'), ('online', 'Online')], max_length=500)),
                ('unitprice', models.CharField(max_length=10000)),
                ('total', models.IntegerField()),
                ('status', models.CharField(blank=True, max_length=10000)),
                ('employee', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='erp_admin.allemployee')),
            ],
        ),
    ]
