# Generated by Django 5.0.6 on 2024-10-04 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_admin', '0008_salesreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendences',
            name='aemp',
        ),
        migrations.RemoveField(
            model_name='attendences',
            name='am',
        ),
        migrations.RemoveField(
            model_name='attendences',
            name='branch_details',
        ),
        migrations.DeleteModel(
            name='leadsentry',
        ),
        migrations.RemoveField(
            model_name='leaves',
            name='branch_details',
        ),
        migrations.RemoveField(
            model_name='leaves',
            name='manager_details',
        ),
        migrations.RemoveField(
            model_name='leaves',
            name='user',
        ),
        migrations.DeleteModel(
            name='purchasereport',
        ),
        migrations.RemoveField(
            model_name='todowork',
            name='fullname',
        ),
        migrations.DeleteModel(
            name='attendences',
        ),
        migrations.DeleteModel(
            name='leaves',
        ),
        migrations.DeleteModel(
            name='todowork',
        ),
    ]
