# Generated by Django 5.0.6 on 2024-10-04 05:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_admin', '0009_remove_attendences_aemp_remove_attendences_am_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_hours', models.DurationField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Full Day', 'Full Day'), ('Half Day', 'Half Day'), ('Absent', 'Absent')], default='Absent', max_length=50)),
                ('aemp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_admin.allemployee')),
                ('am', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_admin.allmanagers')),
                ('branch_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_admin.branches')),
            ],
        ),
        migrations.CreateModel(
            name='leadsentry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.TextField(max_length=1000)),
                ('email', models.TimeField(blank=True, max_length=1000)),
                ('phone', models.CharField(blank=True, max_length=1000)),
                ('companyname', models.CharField(blank=True, max_length=500)),
                ('jobtitle', models.CharField(blank=True, max_length=500)),
                ('website', models.TextField(blank=True)),
                ('source', models.TextField(blank=True)),
                ('followup_date', models.DateField(blank=True)),
                ('followup_method', models.CharField(blank=True, max_length=1200)),
                ('budget', models.CharField(blank=True, max_length=20000)),
                ('leadstatus', models.CharField(blank=True, max_length=1200)),
                ('leadowner', models.EmailField(blank=True, max_length=1200)),
                ('employee', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='erp_admin.allemployee')),
            ],
        ),
        migrations.CreateModel(
            name='leaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=120)),
                ('image', models.FileField(upload_to='media/')),
                ('gender', models.CharField(choices=[('male', ' Male'), ('female', 'Female')], max_length=20)),
                ('leavesdate', models.DateField()),
                ('leaveedate', models.DateField()),
                ('nofdays', models.TextField()),
                ('reasontype', models.TextField()),
                ('reason', models.TextField()),
                ('document', models.FileField(upload_to='media/')),
                ('leavestatus', models.CharField(default='pending', max_length=50)),
                ('email', models.EmailField(max_length=120)),
                ('mobile', models.CharField(max_length=20)),
                ('branch_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_admin.branches')),
                ('employee', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='erp_admin.allemployee')),
                ('manager_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_admin.allmanagers')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='purchasereport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchaseid', models.CharField(max_length=100000)),
                ('dateof_purchase', models.DateField()),
                ('vendor_name', models.CharField(max_length=10000)),
                ('vendor_contact', models.CharField(max_length=10000)),
                ('product_name', models.CharField(max_length=10000)),
                ('product_category', models.CharField(max_length=10000)),
                ('quantity_purchase', models.CharField(max_length=100000)),
                ('payment_method', models.CharField(choices=[('cash on delivery', 'Cash On Delivery'), ('online', 'Online')], max_length=500)),
                ('unitprice', models.CharField(max_length=10000)),
                ('total_purchasecost', models.CharField(max_length=100000)),
                ('status', models.CharField(max_length=10000)),
                ('employee', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='erp_admin.allemployee')),
            ],
        ),
        migrations.CreateModel(
            name='todowork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('work_desc', models.TextField()),
                ('status', models.CharField(max_length=10000)),
                ('delay_reason', models.TextField()),
                ('fullname', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='erp_admin.allemployee')),
            ],
        ),
    ]
