# Generated by Django 5.0.6 on 2024-10-07 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_admin', '0010_attendences_leadsentry_leaves_purchasereport_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaves',
            name='manager_details',
        ),
        migrations.DeleteModel(
            name='salesreport',
        ),
    ]
