# Generated by Django 5.0.6 on 2024-10-07 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_admin', '0012_salesreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadsentry',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='leaves',
            name='branch_details',
        ),
        migrations.RemoveField(
            model_name='leaves',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='leaves',
            name='user',
        ),
        migrations.RemoveField(
            model_name='purchasereport',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='todowork',
            name='fullname',
        ),
        migrations.DeleteModel(
            name='attendences',
        ),
        migrations.DeleteModel(
            name='leadsentry',
        ),
        migrations.DeleteModel(
            name='leaves',
        ),
        migrations.DeleteModel(
            name='purchasereport',
        ),
        migrations.DeleteModel(
            name='todowork',
        ),
    ]
