# Generated by Django 5.0.6 on 2024-10-09 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_admin', '0014_attendences_leadsentry_leaves_purchasereport_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='leaves',
        ),
    ]
