# Generated by Django 5.0.6 on 2024-10-09 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_admin', '0015_delete_leaves'),
    ]

    operations = [
        migrations.CreateModel(
            name='leaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='media/')),
                ('gender', models.CharField(choices=[('male', ' Male'), ('female', 'Female')], max_length=20)),
                ('leavesdate', models.DateField()),
                ('leaveedate', models.DateField()),
                ('nofdays', models.TextField()),
                ('reasontype', models.TextField()),
                ('reason', models.TextField()),
                ('document', models.FileField(upload_to='media/')),
                ('leavestatus', models.CharField(default='pending', max_length=50)),
                ('email', models.EmailField(max_length=120)),
                ('mobile', models.CharField(max_length=20)),
                ('branch_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_admin.branches')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_admin.allemployee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
