# Generated by Django 5.0.6 on 2024-10-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_admin', '0016_leaves'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaves',
            name='employee',
        ),
        migrations.AlterField(
            model_name='leaves',
            name='leavestatus',
            field=models.CharField(blank=True, choices=[('Pending', 'pending'), ('Approved', 'approved'), ('Disapproved', 'disapproved')], default='Pending', max_length=50),
        ),
    ]
