# Generated by Django 5.0.6 on 2024-10-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_admin', '0020_alter_leadsentry_leadowner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadsentry',
            name='email',
            field=models.EmailField(blank=True, max_length=1000),
        ),
    ]
