# Generated by Django 5.0.6 on 2024-10-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_admin', '0021_alter_leadsentry_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todowork',
            name='delay_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='todowork',
            name='work_desc',
            field=models.TextField(blank=True),
        ),
    ]
