# Generated by Django 5.0.6 on 2024-10-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_admin', '0022_alter_todowork_delay_reason_alter_todowork_work_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='quotation_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_header', models.CharField(blank=True, max_length=10000)),
                ('consignee_name', models.CharField(blank=True, max_length=10000)),
                ('consignee_address', models.TextField(blank=True)),
                ('pi_no', models.CharField(blank=True, max_length=10000)),
                ('date', models.DateField(blank=True)),
                ('clearing_port', models.CharField(blank=True, max_length=10000)),
                ('product_name', models.CharField(blank=True, max_length=10000)),
                ('exchange_rate', models.CharField(blank=True, max_length=10000)),
                ('sl_qty_cont', models.CharField(blank=True, max_length=10000)),
                ('sl_inr_per_cont', models.CharField(blank=True, max_length=10000)),
                ('sl_gst_18', models.CharField(blank=True, max_length=10000)),
                ('sl_total_inr', models.CharField(blank=True, max_length=10000)),
                ('cfs_qty_cont', models.CharField(max_length=10000)),
                ('cfs_inr_per_cont', models.CharField(blank=True, max_length=10000)),
                ('cfs_gst_18', models.CharField(blank=True, max_length=10000)),
                ('cfs_total_inr', models.CharField(blank=True, max_length=10000)),
                ('transportation_qty_cont', models.CharField(blank=True, max_length=10000)),
                ('transportation_inr_per_cont', models.CharField(blank=True, max_length=10000)),
                ('transportation_gst_18', models.CharField(blank=True, max_length=10000)),
                ('transportation_total_inr', models.CharField(blank=True, max_length=10000)),
                ('stamp_qty_cont', models.CharField(blank=True, max_length=10000)),
                ('stamp_inr_per_cont', models.CharField(blank=True, max_length=10000)),
                ('stamp_gst_18', models.CharField(max_length=10000)),
                ('stamp_total_inr', models.CharField(max_length=10000)),
                ('agency_qty_cont', models.CharField(blank=True, max_length=10000)),
                ('agency_inr_per_cont', models.CharField(blank=True, max_length=10000)),
                ('agency_gst_18', models.CharField(blank=True, max_length=10000)),
                ('agency_total_inr', models.CharField(blank=True, max_length=10000)),
                ('customduty_qty_cont', models.CharField(max_length=10000)),
                ('customduty_inr_per_cont', models.CharField(max_length=10000)),
                ('customduty_gst_18', models.CharField(max_length=10000)),
                ('customduty_total_inr', models.CharField(max_length=10000)),
                ('oceanfreight_qty_cont', models.CharField(blank=True, max_length=10000)),
                ('oceanfreight_inr_per_cont', models.CharField(blank=True, max_length=10000)),
                ('oceanfreight_gst_18', models.CharField(blank=True, max_length=10000)),
                ('oceanfreight_total_inr', models.CharField(blank=True, max_length=10000)),
                ('round_off', models.CharField(blank=True, max_length=10000)),
                ('total', models.CharField(blank=True, max_length=10000)),
                ('ac_name', models.CharField(blank=True, max_length=10000)),
                ('bank_name', models.CharField(blank=True, max_length=10000)),
                ('ac_no', models.CharField(blank=True, max_length=10000)),
                ('ifsc_code', models.CharField(blank=True, max_length=10000)),
                ('pan_no', models.CharField(blank=True, max_length=10000)),
                ('gst_no', models.CharField(blank=True, max_length=10000)),
            ],
        ),
        migrations.AlterField(
            model_name='todowork',
            name='status',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='todowork',
            name='work_desc',
            field=models.TextField(),
        ),
    ]
