# Generated by Django 5.0.6 on 2024-10-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_admin', '0023_quotation_details_alter_todowork_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation_details',
            name='forty_container',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='quotation_details',
            name='fortyfive_container',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='quotation_details',
            name='twenty_container',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
