# Generated by Django 5.0.6 on 2024-10-18 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_admin', '0024_quotation_details_forty_container_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='quotation_details',
        ),
    ]
