# Generated by Django 5.1.4 on 2024-12-27 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_admin', '0027_remove_allemployee_manager_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobroles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobname', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='branches',
            name='manager_email',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
